const dummyData = {
  response: {
    version: '0.1',
    termsofService: 'http://www.wunderground.com/weather/api/d/terms.html',
    features: {
      conditions: 1,
    },
  },
  current_observation: {
    image: {
      url: 'http://icons.wxug.com/graphics/wu2/logo_130x80.png',
      title: 'Weather Underground',
      link: 'http://www.wunderground.com',
    },
    display_location: {
      full: 'Des Moines, IA',
      city: 'Des Moines',
      state: 'IA',
      state_name: 'Iowa',
      country: 'US',
      country_iso3166: 'US',
      zip: '50301',
      magic: '1',
      wmo: '99999',
      latitude: '41.59999847',
      longitude: '-93.61000061',
      elevation: '235.0',
    },
    observation_location: {
      full: 'wx0zmt, Des Moines, Iowa',
      city: 'wx0zmt, Des Moines',
      state: 'Iowa',
      country: 'US',
      country_iso3166: 'US',
      latitude: '41.610870',
      longitude: '-93.565681',
      elevation: '814 ft',
    },
    estimated: {},
    station_id: 'KIADESMO22',
    observation_time: 'Last Updated on September 11, 9:12 PM CDT',
    observation_time_rfc822: 'Mon, 11 Sep 2017 21:12:28 -0500',
    observation_epoch: '1505182348',
    local_time_rfc822: 'Mon, 11 Sep 2017 21:12:32 -0500',
    local_epoch: '1505182352',
    local_tz_short: 'CDT',
    local_tz_long: 'America/Chicago',
    local_tz_offset: '-0500',
    weather: 'Clear',
    temperature_string: '69.4 F (20.8 C)',
    temp_f: 69.4,
    temp_c: 20.8,
    relative_humidity: '63%',
    wind_string: 'Calm',
    wind_dir: 'South',
    wind_degrees: 180,
    wind_mph: 0.0,
    wind_gust_mph: 0,
    wind_kph: 0,
    wind_gust_kph: 0,
    pressure_mb: '1019',
    pressure_in: '30.09',
    pressure_trend: '0',
    dewpoint_string: '56 F (13 C)',
    dewpoint_f: 56,
    dewpoint_c: 13,
    heat_index_string: 'NA',
    heat_index_f: 'NA',
    heat_index_c: 'NA',
    windchill_string: 'NA',
    windchill_f: 'NA',
    windchill_c: 'NA',
    feelslike_string: '69.4 F (20.8 C)',
    feelslike_f: '69.4',
    feelslike_c: '20.8',
    visibility_mi: '10.0',
    visibility_km: '16.1',
    solarradiation: '--',
    UV: '0',
    precip_1hr_string: '0.00 in ( 0 mm)',
    precip_1hr_in: '0.00',
    precip_1hr_metric: ' 0',
    precip_today_string: '0.00 in (0 mm)',
    precip_today_in: '0.00',
    precip_today_metric: '0',
    icon: 'clear',
    icon_url: 'http://icons.wxug.com/i/c/k/nt_clear.gif',
    forecast_url: 'http://www.wunderground.com/US/IA/Des_Moines.html',
    history_url:
      'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KIADESMO22',
    ob_url:
      'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=41.610870,-93.565681',
    nowcast: '',
  },
};

module.exports = dummyData;
